# Generated by Django 3.1.7 on 2021-03-30 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=300)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.CharField(max_length=1000)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PaperKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.keyword')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.paper')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(through='papers.PaperAuthor', to='papers.Author'),
        ),
        migrations.AddField(
            model_name='paper',
            name='key_words',
            field=models.ManyToManyField(through='papers.PaperKeyWord', to='papers.KeyWord'),
        ),
        migrations.AddField(
            model_name='author',
            name='papers',
            field=models.ManyToManyField(through='papers.PaperAuthor', to='papers.Paper'),
        ),
    ]
