# Generated by Django 3.1.7 on 2021-04-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20210331_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaperAuthor',
            new_name='AuthorPaper',
        ),
        migrations.RenameModel(
            old_name='PaperKeyWord',
            new_name='KeyWordPaper',
        ),
    ]
