# Generated by Django 3.1.7 on 2021-04-02 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserClub',
            new_name='ClubMember',
        ),
        migrations.RenameField(
            model_name='clubmember',
            old_name='user',
            new_name='member',
        ),
    ]
