# Generated by Django 3.1.7 on 2021-04-02 19:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectionProposal',
            new_name='Candidate',
        ),
        migrations.RemoveField(
            model_name='election',
            name='proposals',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='elections',
        ),
        migrations.AddField(
            model_name='election',
            name='candidates',
            field=models.ManyToManyField(through='clubs.Candidate', to='clubs.Proposal'),
        ),
        migrations.AddField(
            model_name='election',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.paper'),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 15, 1, 11, 608700)),
        ),
    ]
