# Generated by Django 3.1.7 on 2021-04-04 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20210402_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 14, 45, 27, 459285, tzinfo=utc)),
        ),
    ]
