# Generated by Django 3.1.7 on 2021-04-05 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20210404_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 12, 15, 34, 522868, tzinfo=utc)),
        ),
    ]
