# Generated by Django 3.1.7 on 2021-04-05 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20210405_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='paper',
        ),
        migrations.AddField(
            model_name='vote',
            name='proposal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clubs.proposal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 13, 23, 46, 602309, tzinfo=utc)),
        ),
    ]
