# Generated by Django 3.1.7 on 2021-04-05 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20210405_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 14, 21, 40, 488140, tzinfo=utc)),
        ),
    ]
