# Generated by Django 3.1.7 on 2021-04-05 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
        ('clubs', '0007_auto_20210405_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.paper'),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 15, 12, 53, 703208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='msg',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
