# Generated by Django 3.1.7 on 2021-04-05 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_auto_20210405_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='users',
            new_name='members',
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 15, 42, 20, 320102, tzinfo=utc)),
        ),
    ]
