# Generated by Django 3.1.7 on 2021-04-05 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20210405_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.TimeField(default=datetime.time(17, 36, 50, 61941)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 21, 36, 12, 142859, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(),
        ),
    ]
