# Generated by Django 3.1.7 on 2021-04-05 22:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_auto_20210405_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='start_date',
            new_name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='election',
            name='end_date',
        ),
        migrations.AddField(
            model_name='election',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 22, 15, 43, 503243, tzinfo=utc)),
        ),
    ]
