# Generated by Django 3.1.7 on 2021-04-05 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_auto_20210405_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='submission_date',
            new_name='submission_datetime',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='submission_date',
            new_name='submission_datetime',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='submission_date',
            new_name='submission_datetime',
        ),
        migrations.AlterField(
            model_name='election',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 22, 16, 18, 213101, tzinfo=utc)),
        ),
    ]
