# Generated by Django 3.1.7 on 2021-04-05 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auto_20210405_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 18, 57, 3, 795470)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 22, 56, 49, 958286, tzinfo=utc)),
        ),
    ]
