# Generated by Django 3.1.7 on 2021-04-06 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_auto_20210405_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='reading',
        ),
        migrations.AlterField(
            model_name='election',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 16, 32, 36, 703540, tzinfo=utc)),
        ),
    ]
