# Generated by Django 3.1.7 on 2021-04-06 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_auto_20210406_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 22, 44, 26, 193237, tzinfo=utc)),
        ),
    ]
