# Generated by Django 3.1.7 on 2021-04-08 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_auto_20210408_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 19, 13, 29, 164782, tzinfo=utc)),
        ),
    ]
